import Head from "next/head";
import Image from "next/image";
import styled from "styled-components";

const IndexEl = styled.div`
`;

export default function Index() {
  return (
    <IndexEl>
      <Head>
        <title>HA-P</title>
        <meta name="description" content="Generated by create next app" />
        
      </Head>
    </IndexEl>
  );
}